# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=10, null=True)),
                ('room', models.CharField(max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxLength', models.IntegerField(blank=True, default=200, null=True)),
                ('isEmpty', models.BooleanField(default=True)),
                ('isFull', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('avgTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('lock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queueItems', django_mysql.models.ListCharField(models.CharField(max_length=11), blank=True, max_length=1200, null=True, size=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('sapID', models.CharField(max_length=11, null=True, unique=True)),
                ('department', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=2, null=True)),
                ('div', models.CharField(max_length=1, null=True)),
                ('batch', models.CharField(max_length=2, null=True)),
                ('inQueue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('isFree', models.BooleanField(default=False)),
                ('sapId', models.CharField(max_length=11, null=True, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='queues.Location')),
                ('queue', models.ManyToManyField(blank=True, to='queues.Queue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subscription',
            field=models.ManyToManyField(blank=True, to='queues.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
