# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_auto_20180223_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='register_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='register_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
