# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_auto_20180301_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='queues.Location'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='queue',
            field=models.ManyToManyField(blank=True, null=True, related_name='queue', to='queues.Queue'),
        ),
    ]
