# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_auto_20180304_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='queue',
            field=models.ManyToManyField(blank=True, related_name='queue', to='queues.Queue'),
        ),
    ]
