# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_auto_20180304_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_location', to='queues.Location'),
        ),
    ]
