# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_queue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='queues.Location'),
        ),
    ]
