# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_auto_20180304_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
